// Pure helpers for the monthly carry-forward. Kept free of DB/Prisma imports so
// the selection rules can be unit-tested in isolation.

// Only the base salary is stable month to month. Allowances (medical, travel,
// bonus, …) and reimbursements vary each period and are (re)entered per run, so
// they are deliberately NOT carried forward. Travel/medical/tax are also auto
// regenerated by the engine on recalc.
export const CARRY_FORWARD_COMPONENT_KEYS: ReadonlySet<string> = new Set(['BASIC_SALARY'])

export interface CarryForwardEmployeeStatus {
  // false when the linked user was permanently deleted.
  exists: boolean
  isPayrollActive: boolean
  exitDate: Date | null
}

// An employee is carried into the target period unless they were deleted,
// deactivated, or offboarded before the target period begins. A row with no
// linked user (status === null) is unmapped, not an offboarded employee, so it
// is left untouched.
export function isCarryForwardEligible(
  status: CarryForwardEmployeeStatus | null,
  targetPeriodStart: Date
): boolean {
  if (status === null) return true
  if (!status.exists) return false
  if (!status.isPayrollActive) return false
  if (status.exitDate !== null && status.exitDate.getTime() < targetPeriodStart.getTime()) {
    return false
  }
  return true
}

export interface CarryForwardInputRow {
  componentKey: string
  userId: string | null
}

// Rows to carry forward: the base-salary component only, and only for employees
// still eligible (active, not offboarded, not deleted).
export function selectCarryForwardInputs<T extends CarryForwardInputRow>(
  baseInputs: T[],
  resolveStatus: (userId: string | null) => CarryForwardEmployeeStatus | null,
  targetPeriodStart: Date
): T[] {
  return baseInputs.filter(
    (row) =>
      CARRY_FORWARD_COMPONENT_KEYS.has(row.componentKey) &&
      isCarryForwardEligible(resolveStatus(row.userId), targetPeriodStart)
  )
}
